language: ruby
bundler_args: --without development
before_install:
  - gem update bundler
rvm:
  - 2.4.1
  - jruby-9.1.8.0
  - 2.3.4
  - 2.2.7
  - 2.1.9
  - 2.0.0
  - 1.9.3
  - jruby-9.0.5.0
  - jruby-1.7.26
  - ruby-head
  - jruby-head
  - rbx
jdk:
  - oraclejdk8
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: 1.9.3
    - rvm: rbx
env:
  global:
    - JAVA_OPTS=-Xmx1024m
script: RUBYOPT=-w bundle exec rspec
